# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Set version name and build number"
  lane :set_versions do
    app = load_json(json_path: "../app.json")

    increment_version_number(version_number: app["ios"]["version"])

    increment_build_number(build_number: app["ios"]["buildNumber"])
  end

  desc "Generic function to use firebase_app_distribution plugin"
  lane :distribute_to_firebase do |options|
    app_id = options[:app_id]
    groups = options[:groups]
    ipa_path = options[:ipa_path]
    firebase_cli_token = options[:firebase_cli_token]

    missing_parameters = [app_id, groups, firebase_cli_token, ipa_path].any? { |param| param.nil? }

    if missing_parameters
      raise "Missing required parameters. Make sure to provide all values."
    end

    firebase_app_distribution(
      app: app_id,
      groups: groups,
      ipa_path: ipa_path,
      firebase_cli_token: firebase_cli_token,
      release_notes: File.read("../../release_notes.txt")
    )
  end

  desc "Run gym to build ipa"
  lane :build_ipa do |options|
    scheme = options[:scheme]
    config = options[:config]
    ipa_name = options[:ipa_name]

    missing_parameters = [scheme, config, ipa_name].any? { |param| param.nil? }

    if missing_parameters
      raise "Missing required parameters. Make sure to provide all values."
    end

    gym(
      clean: true,
      scheme: scheme,
      output_name: ipa_name,
      configuration: config,
      export_method: "ad-hoc",
      output_directory: "archives",
      workspace: "Runner.xcworkspace"
    )
  end

  # This is for Firebase distribution.
  lane :release do
    build_ipa(
      scheme: "Runner",
      config: "Release",
      ipa_name: "BeatsBox.ipa"
    )

    distribute_to_firebase(
      groups: "mercury-dev-testers",
      ipa_path: "archives/BeatsBox.ipa",
      app_id: "1:25273579208:ios:77ded63450a5c3bfa997fd"
    )
  end
end
