// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvtPV4cgRwFwQ_VV0tVhu9TLn4nKeDo28',
    appId: '1:25273579208:android:c327636596933a86a997fd',
    messagingSenderId: '25273579208',
    projectId: 'beats-box-ykstudios',
    storageBucket: 'beats-box-ykstudios.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByIzbdTrAf_ivAuEM702KtyrGP-U9M5Es',
    appId: '1:25273579208:ios:77ded63450a5c3bfa997fd',
    messagingSenderId: '25273579208',
    projectId: 'beats-box-ykstudios',
    storageBucket: 'beats-box-ykstudios.appspot.com',
    androidClientId: '25273579208-4gj35inv059mgo7ith6ehbn2b4purh2e.apps.googleusercontent.com',
    iosClientId: '25273579208-sr07urs923096smikejj99ebonovg5gm.apps.googleusercontent.com',
    iosBundleId: 'com.ykstudios.beatsbox',
  );
}
